export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const ALLLIST_REQUEST = 'ALLLIST_REQUEST';
export const ALLLIST_SUCCESS = 'LLLIST_SUCCESS';
export const ALLLIST_ERROR = 'ALLIST_ERROR';
