export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const ALLLIST_REQUEST = 'ALLLIST_REQUEST';
export const ALLLIST_SUCCESS = 'LLLIST_SUCCESS';
export const ALLLIST_ERROR = 'ALLIST_ERROR';

export const DELETE_REQUEST = 'DELETE_REQUEST';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_ERROR = 'DELETE_ERROR';

export const ALLDELETE_REQUEST = 'ALLDELETE_REQUEST';
export const ALLDELETE_SUCCESS = 'ALLDELETE_SUCCESS';
export const ALLDELETE_ERROR = 'ALLDELETE_ERROR';


export const OPTION_REQUEST = 'OPTION_REQUEST';
export const OPTION_SUCCESS = 'OPTION_SUCCESS';
export const OPTION_ERROR = 'OPTION_ERROR';


export const TITLE_REQUEST = 'TITLE_REQUEST';
export const TITLE_SUCCESS = 'TITLE_SUCCESS';
export const TITLE_ERROR = 'TITLE_ERROR';
